#spring.application.name=stukc
#server.port=9090
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/student
#spring.datasource.username=root
#spring.datasource.password=25252525p
app:
  # 备份配置
  backup:
    # 备份数据库
    db: "student"
    # 备份文件存储目录
    dir: "backups"
    # 备份文件最多保留时间。如，5分钟：5m、12小时：12h、1天：1d
    max-age: 30m
mybatis:
  mapper-locations:
    classpath:mapper/*.xml
server:
  port:
    9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 25252525p
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: stu
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      tea:
        url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: tea
        password: tea
        driver-class-name: com.mysql.cj.jdbc.Driver